#!/bin/bash
CPATH=/usr/local/include:/usr/local/include/plibsys
LD_LIBRARY_PATH=/usr/local/lib
export CPATH
export LD_LIBRARY_PATH

cc -o acs acs.c acs_log.c acs_ini.c acs_net.c acs_ast.c acs_jsn.c acs_chk.c acs_cmd.c acs_utl.c -lplibsys -lsofa_c -lm -lrt
