#!/bin/bash

# Get, build and install plibsys library
echo "Building plibsys library"
cd ~
mkdir Downloads
cd Downloads
wget https://github.com/saprykin/plibsys/archive/master.zip
unzip master.zip
mkdir plibsys
cd plibsys
cmake -DCMAKE_BUILD_TYPE=Release ../plibsys-master
make
make install
echo

# Get, build and install SOFA library
echo "Building SOFA library"
cd ~/Downloads
wget http://www.iausofa.org/2019_0722_C/sofa_c-20190722.tar.gz
tar -zxf sofa_c-20190722.tar.gz
cd sofa/20190722/c//src
make 
make test
cp *.a /usr/lib
cp *.h /usr/include
echo

# Build the ACS
echo "Building ACS.exe"
cd ~/ACS
make

echo "ACS.exe  build complete"
