{"CommandName": "TrackEnable",
 "EnableAG"   : "false",
 "EnableMet"  : "false" ,
 "EnableCorr" : "true",
 "EnableOffset" : "true",
 "EnablePMRA" : "false" ,
 "EnablePMDec": "false",
 "EnableZD"   : "false",
 "EnableAzm"  : "false",
 "EnableRot"  : "false"}
